# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b47fbbd7a2798bdefa342301971e612b"
application_url = "https://cloudflare-workers-app.jakub-okseniuk.workers.dev/"
embedded = true
name = "Chmura i flara"
handle = "chmura-i-flara"

[build]
include_config_on_deploy = true
dev_store_url = "furmanek.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://cloudflare-workers-app.jakub-okseniuk.workers.dev/auth/callback",
  "https://cloudflare-workers-app.jakub-okseniuk.workers.dev/auth/shopify/callback",
  "https://cloudflare-workers-app.jakub-okseniuk.workers.dev/api/auth/callback"
]

[pos]
embedded = false
